// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/andrei1998Front/grpc_img_srvr/internal/domain/models"
)

// ListOfImagesGetter is an autogenerated mock type for the ListOfImagesGetter type
type ListOfImagesGetter struct {
	mock.Mock
}

// ListOfImages provides a mock function with given fields: ctx
func (_m *ListOfImagesGetter) ListOfImages(ctx context.Context) ([]*models.ImgInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOfImages")
	}

	var r0 []*models.ImgInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.ImgInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.ImgInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ImgInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewListOfImagesGetter creates a new instance of ListOfImagesGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListOfImagesGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListOfImagesGetter {
	mock := &ListOfImagesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
