// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0--rc2
// source: grpc_img_serv.proto

package grpc_img_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImgServiceClient is the client API for ImgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImgServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (ImgService_UploadClient, error)
	Download(ctx context.Context, in *ImgDownloadRequest, opts ...grpc.CallOption) (ImgService_DownloadClient, error)
	ListOfImages(ctx context.Context, in *ListOfImagesRequest, opts ...grpc.CallOption) (*ListOfImagesResponce, error)
}

type imgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImgServiceClient(cc grpc.ClientConnInterface) ImgServiceClient {
	return &imgServiceClient{cc}
}

func (c *imgServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (ImgService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImgService_ServiceDesc.Streams[0], "/grpc_img_server.ImgService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &imgServiceUploadClient{stream}
	return x, nil
}

type ImgService_UploadClient interface {
	Send(*ImgUploadRequest) error
	CloseAndRecv() (*ImgInfo, error)
	grpc.ClientStream
}

type imgServiceUploadClient struct {
	grpc.ClientStream
}

func (x *imgServiceUploadClient) Send(m *ImgUploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imgServiceUploadClient) CloseAndRecv() (*ImgInfo, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImgInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imgServiceClient) Download(ctx context.Context, in *ImgDownloadRequest, opts ...grpc.CallOption) (ImgService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImgService_ServiceDesc.Streams[1], "/grpc_img_server.ImgService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &imgServiceDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ImgService_DownloadClient interface {
	Recv() (*ImgDownloadResponce, error)
	grpc.ClientStream
}

type imgServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *imgServiceDownloadClient) Recv() (*ImgDownloadResponce, error) {
	m := new(ImgDownloadResponce)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imgServiceClient) ListOfImages(ctx context.Context, in *ListOfImagesRequest, opts ...grpc.CallOption) (*ListOfImagesResponce, error) {
	out := new(ListOfImagesResponce)
	err := c.cc.Invoke(ctx, "/grpc_img_server.ImgService/ListOfImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImgServiceServer is the server API for ImgService service.
// All implementations must embed UnimplementedImgServiceServer
// for forward compatibility
type ImgServiceServer interface {
	Upload(ImgService_UploadServer) error
	Download(*ImgDownloadRequest, ImgService_DownloadServer) error
	ListOfImages(context.Context, *ListOfImagesRequest) (*ListOfImagesResponce, error)
	mustEmbedUnimplementedImgServiceServer()
}

// UnimplementedImgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImgServiceServer struct {
}

func (UnimplementedImgServiceServer) Upload(ImgService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedImgServiceServer) Download(*ImgDownloadRequest, ImgService_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedImgServiceServer) ListOfImages(context.Context, *ListOfImagesRequest) (*ListOfImagesResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOfImages not implemented")
}
func (UnimplementedImgServiceServer) mustEmbedUnimplementedImgServiceServer() {}

// UnsafeImgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImgServiceServer will
// result in compilation errors.
type UnsafeImgServiceServer interface {
	mustEmbedUnimplementedImgServiceServer()
}

func RegisterImgServiceServer(s grpc.ServiceRegistrar, srv ImgServiceServer) {
	s.RegisterService(&ImgService_ServiceDesc, srv)
}

func _ImgService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImgServiceServer).Upload(&imgServiceUploadServer{stream})
}

type ImgService_UploadServer interface {
	SendAndClose(*ImgInfo) error
	Recv() (*ImgUploadRequest, error)
	grpc.ServerStream
}

type imgServiceUploadServer struct {
	grpc.ServerStream
}

func (x *imgServiceUploadServer) SendAndClose(m *ImgInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imgServiceUploadServer) Recv() (*ImgUploadRequest, error) {
	m := new(ImgUploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ImgService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImgDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImgServiceServer).Download(m, &imgServiceDownloadServer{stream})
}

type ImgService_DownloadServer interface {
	Send(*ImgDownloadResponce) error
	grpc.ServerStream
}

type imgServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *imgServiceDownloadServer) Send(m *ImgDownloadResponce) error {
	return x.ServerStream.SendMsg(m)
}

func _ImgService_ListOfImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgServiceServer).ListOfImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_img_server.ImgService/ListOfImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgServiceServer).ListOfImages(ctx, req.(*ListOfImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImgService_ServiceDesc is the grpc.ServiceDesc for ImgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_img_server.ImgService",
	HandlerType: (*ImgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOfImages",
			Handler:    _ImgService_ListOfImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _ImgService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _ImgService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc_img_serv.proto",
}
